spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    embedded:
      version: 3.5.5
management:
  metrics:
    tags:
      application: footy-pickup
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

