

###
### CreatePlayerNo1
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "Sagar",
  "lastName" : "Poudel",
  "shirtNumber": 11,
  "playerPosition": "LW",
  "isCaptain": true
}
> {%
    client.global.set("p1", response.body.id);
%}
### CreatePlayerNo2
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "Rahul",
  "lastName" : "Gauli",
  "shirtNumber": 10,
  "playerPosition": "CM",
  "isCaptain": false
}
> {%
    client.global.set("p2", response.body.id);
%}
### CreatePlayerNo3
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "Angel",
  "lastName" : "Gyawali",
  "shirtNumber": 5,
  "playerPosition": "CB",
  "isCaptain": false
}
> {%
    client.global.set("p3", response.body.id);
%}
### CreatePlayerNo4
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "Kabi",
  "lastName" : "P",
  "shirtNumber": 7,
  "playerPosition": "ST",
  "isCaptain": true
}
> {%
    client.global.set("pA", response.body.id);
%}
### CreatePlayerNo5
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "Rajan",
  "lastName" : "P",
  "shirtNumber": 6,
  "playerPosition": "CB",
  "isCaptain": false
}
> {%
    client.global.set("pB", response.body.id);
%}
### CreatePlayerNo6
POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "firstName" : "XXXX",
  "lastName" : "XXX",
  "shirtNumber": 1,
  "playerPosition": "GK",
  "isCaptain": false
}
> {%
    client.global.set("pC", response.body.id);
%}

### CreateTeam1
POST http://localhost:8080/v1/teams
Content-Type: application/json

{
  "name": "Tallwood FC"
}
> {%
    client.global.set("tallwood", response.body.id);
%}

### CreateTeam2
POST http://localhost:8080/v1/teams
Content-Type: application/json

{
  "name": "Lakeside FC"
}
> {%
    client.global.set("lakeside", response.body.id);
%}

### AddPlayer1ToTallwood
POST http://localhost:8080/v1/teams/{{tallwood}}/player/{{p1}}/add
### AddPlayer2ToTallwood
POST http://localhost:8080/v1/teams/{{tallwood}}/player/{{p2}}/add
### AddPlayer3ToTallwood
POST http://localhost:8080/v1/teams/{{tallwood}}/player/{{p3}}/add

### AddPlayerAToTallwood
POST http://localhost:8080/v1/teams/{{lakeside}}/player/{{pA}}/add
### AddPlayerBToTallwood
POST http://localhost:8080/v1/teams/{{lakeside}}/player/{{pC}}/add
### AddPlayerCToTallwood
POST http://localhost:8080/v1/teams/{{lakeside}}/player/{{pB}}/add

### CreateNewMatch
POST http://localhost:8080/v1/matches
Content-Type: application/json

{
  "numberOfPlayersPerSide": 3
}
> {%
    client.global.set("match", response.body.id);
%}

### AddLakesideToMatch
POST http://localhost:8080/v1/matches/{{match}}/team/{{lakeside}}/add

### AddTallwoodToMatch
POST http://localhost:8080/v1/matches/{{match}}/team/{{tallwood}}/add

### StartTheMatch
POST http://localhost:8080/v1/matches/{{match}}/start
Content-Type: application/json

{}

### RegisterGoalByP1
POST http://localhost:8080/v1/matches/{{match}}/team/{{tallwood}}/player/{{p1}}/goal
Content-Type: application/json

{}

### RegisterGoalByPA
POST http://localhost:8080/v1/matches/{{match}}/team/{{lakeside}}/player/{{pA}}/goal
Content-Type: application/json

{}

### RegisterGoalByP2
POST http://localhost:8080/v1/matches/{{match}}/team/{{tallwood}}/player/{{p2}}/goal
Content-Type: application/json

{}

### EndTheMatch
POST http://localhost:8080/v1/matches/{{match}}/end
Content-Type: application/json

{}
